require("eftw.plugins-setup")
require("eftw.core.options")
require("eftw.core.keymaps")
require("eftw.core.colorscheme")
require("eftw.plugins.comment")
require("eftw.plugins.nvim-tree")
require("eftw.plugins.lualine")
-- require("eftw.plugins.obsidian")
-- require("eftw.plugins.telescope")
-- require("eftw.plugins.nvim-cmp")
-- require("eftw.plugins.lsp.mason")
-- require("eftw.plugins.lsp.lspsaga")
-- require("eftw.plugins.lsp.lspconfig")
-- require("eftw.plugins.lsp.null-ls")
-- require("eftw.plugins.autopairs")
-- require("eftw.plugins.treesitter")
-- require("eftw.gitsigns")
