theme = "bogster"

[editor]
line-number = "relative"
mouse = false
auto-format = false
color-modes = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer", "spacer"]
bufferline = "always"
shell = ["nu", "--env-config", "~\\AppData\\Roaming\\nushell\\env.nu", "--config", "~\\AppData\\Roaming\\nushell\\config.nu", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode"]
center = ["file-name"]
right = ["position", "file-type", "version-control"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
